from abc import ABC, abstractmethod
from typing import Dict, List, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class Signal:
    """Trading signal generated by a strategy"""

    def __init__(self, market_id: str, outcome: str, action: str,
                 size: float, price: float, confidence: float = 0.5,
                 reason: str = ""):
        self.market_id = market_id
        self.outcome = outcome
        self.action = action  # BUY or SELL
        self.size = size
        self.price = price
        self.confidence = confidence  # 0 to 1
        self.reason = reason
        self.timestamp = datetime.now()

    def to_dict(self) -> Dict:
        return {
            'market_id': self.market_id,
            'outcome': self.outcome,
            'action': self.action,
            'size': self.size,
            'price': self.price,
            'confidence': self.confidence,
            'reason': self.reason,
            'timestamp': self.timestamp.isoformat()
        }

    def __repr__(self):
        return f"Signal({self.action} {self.size} {self.outcome} @ {self.price} - {self.reason})"


class BaseStrategy(ABC):
    """Base class for trading strategies"""

    def __init__(self, name: str, config: Dict = None):
        self.name = name
        self.config = config or {}
        self.enabled = True
        self.signals_generated = 0

    @abstractmethod
    async def analyze(self, market: Dict, prices: Dict) -> List[Signal]:
        """
        Analyze a market and generate trading signals

        Args:
            market: Market data from Polymarket API
            prices: Current prices for market outcomes

        Returns:
            List of trading signals
        """
        pass

    def validate_signal(self, signal: Signal) -> bool:
        """Validate a signal before execution"""
        if signal.price <= 0 or signal.price > 1:
            logger.warning(f"Invalid price {signal.price} for signal")
            return False

        if signal.size <= 0:
            logger.warning(f"Invalid size {signal.size} for signal")
            return False

        if signal.confidence < 0 or signal.confidence > 1:
            logger.warning(f"Invalid confidence {signal.confidence} for signal")
            return False

        return True

    def enable(self):
        """Enable strategy"""
        self.enabled = True
        logger.info(f"Strategy {self.name} enabled")

    def disable(self):
        """Disable strategy"""
        self.enabled = False
        logger.info(f"Strategy {self.name} disabled")

    async def generate_signals(self, market: Dict, prices: Dict) -> List[Signal]:
        """Generate signals (wrapper that handles enable/disable)"""
        if not self.enabled:
            return []

        try:
            signals = await self.analyze(market, prices)
            valid_signals = [s for s in signals if self.validate_signal(s)]
            self.signals_generated += len(valid_signals)
            return valid_signals
        except Exception as e:
            logger.error(f"Error in strategy {self.name}: {e}")
            return []

    def get_stats(self) -> Dict:
        """Get strategy statistics"""
        return {
            'name': self.name,
            'enabled': self.enabled,
            'signals_generated': self.signals_generated
        }
